-- AlterEnum
ALTER TYPE "ApplicationStatus" RENAME VALUE 'REVIEWING' TO 'SCREENING';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'SHORTLIST' AFTER 'SCREENING';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'HIRED' AFTER 'OFFER';
ALTER TYPE "ApplicationStatus" ADD VALUE IF NOT EXISTS 'WITHDRAWN' AFTER 'REJECTED';
